### ISSUE TITLE
An unhandled exception has occurred

### ISSUE THREAD

**Issue by PEWdiePUGxd** [TEdit/Terraria-Map-Editor#1036] opened 2017-11-21 16:15 UTC
What were you doing when the issue occured?
I started Tedit
Can you reproduce the issue?
Yes
What version of Terraria are you using?
v1.3.5.1

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1492062/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2017-11-21 17:18
Duplicate of #751

**Closed** 2017-11-21 17:19 UTC
Labels: Bug
