### ISSUE TITLE
After editing certain world, load always fails, not with other worlds

### ISSUE THREAD

**Issue by dspsx** [TEdit/Terraria-Map-Editor#1221] opened 2020-05-22 02:14 UTC
For some reason whenever I do anything in TEdit to my main world and then try to load it in terraria it says load failed and I have to load the backup. I tried switching the .bak and .wld files around but that didn't work. It only happens with my main world. I have been using TEdit constantly on this world since the beta4 version, so maybe I did something previously. Any idea on how to fix it?

**Comment by Winston-Lu** [comment] 2020-05-22 02:51
Same here — even with no changes, loading a world in TEdit and saving it doesn't seem to work. I'd assume its something to do with the world headers or data that its adding. Also worth noting I'm running Terraria 1.4.0.3 TEdit4 Beta 5. I couldn't find any log file either in Documents\Terraria or in the Steam install

**Comment by BinaryConstruct** [comment] 2020-05-22 04:22
Duplicate of #1200

**Closed by BinaryConstruct** 2020-05-22 04:22 UTC
