### ISSUE TITLE
The program will now exit.

### ISSUE THREAD

**Issue by Kamikazo** [TEdit/Terraria-Map-Editor#752] opened 2016-03-13 00:23 UTC
I have all the programs what need TEdit, and yesterday the Tedit work normal, and today dont open.
I need help, please.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/170694/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2016-03-14 05:16
Duplicate of #751

**Closed by BinaryConstruct** 2016-03-14 05:16 UTC
