### ISSUE TITLE
Opening TEdit ends up resulting .exe stopped working

### ISSUE THREAD

**Issue by Spurdos** [TEdit/Terraria-Map-Editor#1276] opened 2020-06-04 14:58 UTC
I downloaded TEdit from its official source to use. Prior to downloading, I did the requirements on the things needed in order for TEdit to work, read the issues and such to know what to do when the program stops working, etc. Once its downloaded, I made a folder in my desktop named TEdit to easily access it. I opened the ,exe file after unzipping to the folder. The .exe worked for roughly  8 seconds before the notification "TEdit has stopped working" appeared. Despite the program actually run in the task manager's processes tab, it didn't show a window open but only the notification of it not working. It would be wonderful if there's something I could do to make it work once more. The TEdit I used to operate worked back during the 1.3.5 update.

The version of my Terraria is 1.4.0.4

In case you need the .log file, here:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4730816/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2020-06-04 15:02
This looks like a duplicate of #751 based on your error log. Unfortunatly this error seems to be related to the machine and some underlying frameworks used by TEdit. There are some troubleshooting tips on that issue that might help.

**Closed by BinaryConstruct** 2020-06-04 15:02 UTC
