### ISSUE TITLE
Suggested Feature: Defined Boundaries

### ISSUE THREAD

**Issue by CeterisParibus51** [TEdit/Terraria-Map-Editor#1862] opened 2023-06-13 20:43 UTC
**Is your feature request related to a problem? Please describe.**
T Edit shows the entire world, which is great, however, there is no clear indicator of what is or isn't out of bounds for a particular world size, this can be annoying when building and suddenly part of the build is below the cutoff in the underworld, or above the cutoff in space, or beyond the cutoffs for the oceans at the left and right of the world.

**Describe the solution you'd like**
either a simple wire frame box around this boundary to serve as a guideline for where the playable area ends, or a change in the background color on the editor to specify these areas. maybe putting this on a plugin or toggle-able option as to weather or not the boundaries are displayed could be a happy medium so any users who don't wanna see the boundaries don't have to, and those of us that do could just enable the indicator.

**Comment by BinaryConstruct** [comment] 2023-06-15 01:11
Closing as dupe of #1691, use that issue for tracking

**Closed** 2023-06-15 01:12 UTC
