### ISSUE TITLE
Only ever dirt

### ISSUE THREAD

**Issue by Alixirrrr** [TEdit/Terraria-Map-Editor#1902] opened 2024-07-03 13:09 UTC
Tedit only places dirt no matter what tools I use
Open Tedit
its just dirt

**Expected behavior**
To place the correct blocks

  Windows 10
 - Version [Tedit 4 5.00 beta]
 - Terraria Version [e.g. 1.4.4.9]

**Comment by BinaryConstruct** [comment] 2024-07-03 20:48
Duplicate of #1899

**Closed by BinaryConstruct** 2024-07-03 20:48 UTC
