### ISSUE TITLE
Dirt drawn regardless of brush/pencil settings

### ISSUE THREAD

**Issue by Presistedcrib** [TEdit/Terraria-Map-Editor#1900] opened 2024-07-02 18:23 UTC
**Describe the bug**
Dirt, the brush and the pencil draw dirt. I love dirt, but my god I need some other blocks if this is going to be a useful tool.

1. Use the brush tool to draw anything other than dirt.
2. Dirt.

**Expected behavior**
I expect to be able to not draw dirt. This even happens with the eraser tool.

**Comment by BinaryConstruct** [comment] 2024-07-03 20:48
Duplicate of #1899

**Closed by BinaryConstruct** 2024-07-03 20:48 UTC
Labels: Duplicate
