### ISSUE TITLE
TEdit doesn't work

### ISSUE THREAD

**Issue by ItzAdel** [TEdit/Terraria-Map-Editor#1107] opened 2018-09-01 16:36 UTC
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2342520/TEditLog.txt)
Opened as the administrator, put compatibility with Windows 7, put on the new driver, put on new XNA and .NET framework.
Please answer how to fix it?
(Sorry to send in the notebook, there are many characters)

**Comment by BinaryConstruct** [comment] 2018-09-01 16:38
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/742 (TEdit doesn't work on latest update!?), https://github.com/TEdit/Terraria-Map-Editor/issues/743 (tedit not working), https://github.com/TEdit/Terraria-Map-Editor/issues/775 (TEdit does not work), https://github.com/TEdit/Terraria-Map-Editor/issues/945 (Tedit doesn't work for me!), and https://github.com/TEdit/Terraria-Map-Editor/issues/873 (TEdit.exe stopped working).

**Comment by ItzAdel** [comment] 2018-09-01 16:40
I have a GPU AMD R7 250X

**Comment by BinaryConstruct** [comment] 2018-09-06 01:44
Duplicate of #751

**Closed by BinaryConstruct** 2018-09-06 01:44 UTC
Labels: Bug
