### ISSUE TITLE
tedit won't open error pops up

### ISSUE THREAD

**Issue by TMiner99** [TEdit/Terraria-Map-Editor#769] opened 2016-04-26 21:58 UTC
i have installed the new beta multiple times amd upgraded to .netframework 4.5 
i need help
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/237581/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2016-04-27 19:48
Duplicate of #751

**Closed by BinaryConstruct** 2016-04-27 19:48 UTC
