### ISSUE TITLE
Can't save, stuck at validating world.

### ISSUE THREAD

**Issue by domaik** [TEdit/Terraria-Map-Editor#1219] opened 2020-05-21 20:17 UTC
With both beta 4 and beta 5 when I try to save any changes to my world TEdit gets stuck at "validating" world and doesn't create the save file at all.

EDIT: tried saving under different names and different directories. Still nothing. Tried zooming in while TEdit said "validating world" and the program crashed.

**Comment by BinaryConstruct** [comment] 2020-05-21 21:06
Duplicate of #1200

**Closed by BinaryConstruct** 2020-05-21 21:06 UTC
