### ISSUE TITLE
Tedit doesn't work for me!

### ISSUE THREAD

**Issue by Shinaii** [TEdit/Terraria-Map-Editor#945] opened 2016-12-22 18:55 UTC
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/669574/TEditLog.txt)

i Have:
win7 Professional 64bit
DotNet Framework 4.5.2

**Comment by BinaryConstruct** [comment] 2016-12-22 19:18
Duplicate of #751

**Closed** 2016-12-29 19:09 UTC
