### ISSUE TITLE
TEDIT DON'T WANT TO LAUNCH (unhandled exception)

### ISSUE THREAD

**Issue by crystalik2** [TEdit/Terraria-Map-Editor#1045] opened 2017-12-29 12:15 UTC
I downloaded the latest version of tedit and unzipped to a folder on my deckstop. When I start exe file, I just had a unhandled exception :(

## What were you doing when the issue occured?

My browser and steam was open. So, the system wasn't loaded too much.

## Can you reproduce the issue?

Yes. I had been trying to start tedit many times, but unsuccessfully.

## What version of Terraria are you using?

The latest - 1.3.5.2

## Post relevant contents of log or attach log file _**(very important)**_:

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1593077/TEditLog.txt)

## PC CONFIGURATION

Processor - Intel Core i5 4690 @ 3.50GHz
VIDEO - 2047MB NVIDIA GeForce GTX 750 Ti
RAM - 16,0ГБ Dual-Channel DDR3 @ 799MHz
Motherboard - ASUSTeK COMPUTER INC. Z97-K

**Comment by BinaryConstruct** [comment] 2018-02-26 19:29
Duplicate of #751

**Closed by BinaryConstruct** 2018-02-26 19:29 UTC
Labels: Bug
