### ISSUE TITLE
TEdit3_BETA_v3.7.16150.1634 crashes on startup, unable to install

### ISSUE THREAD

**Issue by Lestorne** [TEdit/Terraria-Map-Editor#796] opened 2016-05-31 00:27 UTC
Crash log below:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	teditxna.exe
  Problem Signature 02:	3.7.16150.1634
  Problem Signature 03:	574b1a33
  Problem Signature 04:	SharpDX
  Problem Signature 05:	2.6.3.0
  Problem Signature 06:	5450f8ae
  Problem Signature 07:	a4d
  Problem Signature 08:	14
  Problem Signature 09:	SharpDX.SharpDXException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	d1bb
  Additional Information 2:	d1bb4ba09f73bbd1119123a7b9bfc54e
  Additional Information 3:	6d20
  Additional Information 4:	6d20b092079ebe1d87650d40ee3549c3

**Comment by BinaryConstruct** [comment] 2016-05-31 14:16
Probably a duplicate of #751

**Closed by BinaryConstruct** 2016-05-31 14:16 UTC
