### ISSUE TITLE
Error when i start programm

### ISSUE THREAD

**Issue by XomkaShou** [TEdit/Terraria-Map-Editor#1098] opened 2018-07-28 15:07 UTC
Have that Issue. Error when I start Terraria Map Editor
## What were you doing when the issue occured?
Install old versions... But that not work

## Can you reproduce the issue?
This error happens when I start programm

## What version of Terraria are you using?
1.3.5.3 Steam Version

## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2238068/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2018-07-28 15:08
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/946 (Error.), https://github.com/TEdit/Terraria-Map-Editor/issues/703 (Error), https://github.com/TEdit/Terraria-Map-Editor/issues/320 (Error), https://github.com/TEdit/Terraria-Map-Editor/issues/297 (Error When Editing Worlds), and https://github.com/TEdit/Terraria-Map-Editor/issues/459 (Starting up TEdit Problem).

**Comment by BinaryConstruct** [comment] 2018-08-16 21:14
Duplicate of #751

**Closed by BinaryConstruct** 2018-08-16 21:14 UTC
Labels: Bug
