### ISSUE TITLE
TEdit Ain't Working Properly..

### ISSUE THREAD

**Issue by Lord-Garen** [TEdit/Terraria-Map-Editor#1092] opened 2018-07-04 13:43 UTC
## What were you doing when the issue occured?
Waiting for the Program to start
## Can you reproduce the issue?
Yes....We can talk on Discord @ Garen 3322#4976
## What version of Terraria are you using?
v1.3.5.3 & vv3.10.18105.218 of TEdit
## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2163380/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2018-07-04 13:44
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/743 (tedit not working), https://github.com/TEdit/Terraria-Map-Editor/issues/775 (TEdit does not work), https://github.com/TEdit/Terraria-Map-Editor/issues/590 (Tedit (latest version) not working visually), https://github.com/TEdit/Terraria-Map-Editor/issues/945 (Tedit doesn't work for me!), and https://github.com/TEdit/Terraria-Map-Editor/issues/879 (TEdit.exe has stopped working).

**Comment by BinaryConstruct** [comment] 2018-07-06 01:44
Duplicate of #751

**Closed by BinaryConstruct** 2018-07-06 01:44 UTC
Labels: Bug
