### ISSUE TITLE
TEdit starts crashing 

### ISSUE THREAD

**Issue by XrustKostey** [TEdit/Terraria-Map-Editor#1260] opened 2020-05-31 06:53 UTC
On first start TEdit works fine, but then it starts crashing.
Terraria GOG version
.Net Framework 4.8
DirectX 11

Problem Event Name: CLR20r3
  Problem 01 Signature:	TEdit.exe
  Problem Signature 02:	4.0.0.0
  Problem 03 Signature:	b7e9d531
  Problem 04 Signature:	SharpDX
  Problem 05 Signature:	4.0.1.0
  Problem Signature 06:	592da585
  Problem Signature 07:	136
  Problem Signature 08:	14
  Problem Signature 09:	System.InvalidOperationException
  Operating system version:	6.1.7601.2.1.0.256.48
  Location ID:	1049
  Additional Information 1:	4553
  Additional Information 2:	4553daf2d6cded34585efb8f7c75d385
  Additional Information 3:	e929
  Additional Information 4:	e9290500b25e23b2af1b9b98fa9cf990

**Comment by BinaryConstruct** [comment] 2020-05-31 15:02
Do you have a log file? This issue has come up a couple times, seems to be related to rendering.

**Comment by BinaryConstruct** [comment] 2020-05-31 15:02
Duplicate of #1256

**Closed** 2020-05-31 15:02 UTC
