### ISSUE TITLE
Error - No application is associated with the specified file for this operation

### ISSUE THREAD

**Issue by Walkman100** [TEdit/Terraria-Map-Editor#633] opened 2015-08-03 16:13 UTC
When clicking on <kbd>Wiki</kbd>, <kbd>Update</kbd> or <kbd>Download New XML Data</kbd> in the `Help` menu:
```
An unhandled exception has occured. Please copy the log from:
C:\Users\<username>\Documents\My Games\Terraria\TEditLog.txt
 to the GitHub Issues list.
The program will now exit.
```
Log:
```
08-03-2015 18:09: Starting TEdit 3.5.14228.27 
08-03-2015 18:09: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-03-2015 18:09: .Net >= 4.0 
08-03-2015 18:09: XNA 4.0 
08-03-2015 18:09: Terraria Data Path: B:\Working Games\Terraria\Current Data\Content 
08-03-2015 18:09: Creating Undo cache: C:\Users\<username>\AppData\Roaming\TEdit\undo_605835335 
08-03-2015 18:09: Error - No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at TEditXna.ViewModel.WorldViewModel.<get_LaunchWikiCommand>b__2()
[...]
```

**Comment by SBlogic** [comment] 2015-08-03 17:24
Looking into this.  It just attempts to use a URL to spawn a process.  If you open a command prompt and type `start http://wwww.google.com`, what happens?

**Comment by Walkman100** [comment] 2015-08-03 18:59
![2015-8-3_20 54 18 216](https://cloud.githubusercontent.com/assets/5454764/9045197/d834128a-3a21-11e5-915e-672f81258267.png)
`The system cannot execute the specified program.`
It's because I don't have a program registered for the http or https protocols:
![2015-8-3_20 58 28 335](https://cloud.githubusercontent.com/assets/5454764/9045303/68843cd4-3a22-11e5-969c-b2b7116a844c.png)
I want to set it to Chrome, but since Chrome isn't there I rather leave it not set.

**Comment by SBlogic** [comment] 2015-08-03 20:13
Technically this isn't exactly an issue with TEdit, though it definitely needs a try/catch around the Process.Start() to keep it from bombing gracelessly when the external call fails.  Something's definitely wrong with your file/protocol associations (not only is Chrome missing, but Opera appears twice).

At the very least, you might want to go into the Internet Settings Control Panel, go to the Programs tab, then set Internet Explorer as the default browser.  It should try to fix the HTTP and HTTPS handlers.  Once that's done, try launching a URL again to make sure it works.  Then repair/reinstall Chrome, and set it to your default browser.  Hopefully that will straighten things out.

**Comment by Walkman100** [comment] 2015-08-03 21:19
> Technically this isn't exactly an issue with TEdit

Well, It means I'd have to find the pages it's supposed to go to myself, not that I'm lazy (I like to think) but potentially someone could find the wrong page.
> Something's definitely wrong with your file/protocol associations (not only is Chrome missing, but Opera appears twice).

Because I have two versions of Opera - v12 (engine made by Opera), and v28+ (uses the chromium engine). Don't know why Chrome doesn't have an entry.
I actually like not having browsers launching automatically, some programs like to spam pages in the browser -_- (e.g. "updates" or "whats new" pages that I couldn't care less about)

In the programs that I make, I always have a Try/Catch around launching a URL, and if it can't start the URL then it gives an option to copy it to clipboard, e.g. (in VB.Net):
```vb
Try
    Process.Start(urlToOpen)
Catch
    If MsgBox("Unable to launch URL, copy to clipboard instead?", MsgBoxStyle.YesNo + MsgBoxStyle.Exclamation) = MsgBoxResult.Yes Then
        Clipboard.SetText(urlToOpen)
    End If
End Try
```

**Comment by SBlogic** [comment] 2015-08-04 00:23
That's pretty similar to the change I made, though it didn't cross my mind to copy the URL to the clipboard.  I've adapted the code to do this.

I've committed the changes to my fork.  Any chance you could download and try it to see if it's better behaved and works as intended?  Note:  This won't fix a crash with the "Update" or "Download New XML Data" menu items, which work differently.  (If this works better, I might be able to update those as well.)

**Comment by Walkman100** [comment] 2015-08-04 02:12
> This won't fix a crash with the "Update" or "Download New XML Data" menu items

So it fixes the Wiki item? Don't think there are any others that start URLs directly.

**Comment by Walkman100** [comment] 2015-08-04 02:32
:+1: Yup - copies the link to the clipboard when I click `Yes`. It doesn't show a style though:
![image](https://cloud.githubusercontent.com/assets/5454764/9051934/b58771a6-3a61-11e5-9317-8f6aea796c09.png)
(style as in warning or error symbol)

**Comment by SBlogic** [comment] 2015-08-04 02:53
Added MessageBoxIcon.Exclamation.

There's another method that also uses Process.Start() to load a URL, hidden behind the update check.  Currently Help|Update and Help|Download New XML Data point to the same function which also launches a URL.  It's in a different place for a reason that's not immediately obvious to me, but I'll look into wrapping this as well.

**Closed** 2015-08-12 06:36 UTC

**Comment by ayus786** [comment] 2020-05-21 07:02
This error is coming in my powershell plzzzz help.....


Program 'Set-Location' failed to run: No application is associated with the specified file for this operationAt line:1
char:1
+ cd "C:\Users\ayush\Documents\ML project 1"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ cd "C:\Users\ayush\Documents\ML project 1"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
