### ISSUE TITLE
line through natrual backround after using tedit

### ISSUE THREAD

**Issue by Eudoxxie** [TEdit/Terraria-Map-Editor#1790] opened 2022-10-31 10:16 UTC
when saving a world after editing it in tedit somewhere in the world a hard line happens in the natural background wall that spans the whole world

1. any time i save a world on tedit this happens.

![Screenshot (400)](https://user-images.githubusercontent.com/117078510/198984840-b5cd047c-bbdd-4bcc-8460-2783eb963a83.png)

this has been happening on every version of tedit i try

**Comment by RussDev7** [comment] 2022-10-31 16:19
This would appear to be a bug. What size world are you currently playing on?

**Comment by BinaryConstruct** [comment] 2022-11-01 18:51
Duplicate of #1534

**Closed by BinaryConstruct** 2022-11-01 18:51 UTC

**Comment by dddse2** [comment] 2022-11-09 04:39
Also happened to me, the world is a medium size.
