### ISSUE TITLE
Unable to save changes to master mode worlds generated in 1.4.0.1

### ISSUE THREAD

**Issue by FancyVans** [TEdit/Terraria-Map-Editor#1222] opened 2020-05-22 02:49 UTC
Multiple issues with trying to edit master mode worlds generated in 1.4.0.1.
- Opening the world shows a "World File Error"
- Attempting to save changes to worlds shows a "World Modified" error box
- Even with trying "Overwrite" option, no changes are saved to the world once loaded

Note: Master mode worlds generated in 1.4.0.3 work perfectly with no errors and edits will show up in-game.

## What were you doing when the issue occured?
I was attempting to save editing changes made to a world generated on May 16th, during the 1.4.0.1 Patch.

## Can you reproduce the issue?
Yes.
TEdit will ask to force load the world file every time when trying to open the world.
TEdit will ask to attempt to overwrite.
No changes are ever saved to the world when loading the world in-game, or when loading the world in TEdit again.

## What version of Terraria are you using?
I am using Terraria version 1.4.0.3, but the world file was generated in 1.4.0.1
I am using TEdit version 4.0.0-beta5.

## Post relevant contents of log or attach log file _**(very important)**_:
World File Error when attemping to open the world file
![World File Error](https://user-images.githubusercontent.com/63953026/82625993-4bd59900-9bef-11ea-8510-c7d89790a678.PNG)

Error message when attempting to save changes to the world
![World Modified](https://user-images.githubusercontent.com/63953026/82626036-660f7700-9bef-11ea-9b47-d3ac0d8958c8.PNG)

The world file zipped up. Only contains the file for the world
[The_Sweaty_Shrine_of_Mice.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4665817/The_Sweaty_Shrine_of_Mice.zip)

**Comment by FancyVans** [comment] 2020-05-22 02:52
Also as another bug, TEdit will always crash when attempting to zoom close enough to render blocks as they appear in-game.

**Comment by BinaryConstruct** [comment] 2020-05-22 04:21
The Invalid Tile Entities is a giveaway: duplicate of #1200

**Closed by BinaryConstruct** 2020-05-22 04:21 UTC
