### ISSUE TITLE
TEdit 4.0 beta 16 bug

### ISSUE THREAD

**Issue by Merzlan** [TEdit/Terraria-Map-Editor#1285] opened 2020-06-06 06:21 UTC
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/4739432/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2020-06-06 12:40
This is a duplicate of #751, see that issues for tips on resolving it.

**Comment by BinaryConstruct** [comment] 2020-06-06 12:40
This is a duplicate of #751, see that issues for tips on resolving it.

**Closed** 2020-06-08 04:08 UTC
