### ISSUE TITLE
TEdit won't to start

### ISSUE THREAD

**Issue by IMSCRUB** [TEdit/Terraria-Map-Editor#1060] opened 2018-01-28 10:59 UTC
My TEdit won't start, with error named "Unhandled Exeption". I'm check the log and find - [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved]
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1671010/TEditLog.txt)
Windows 7, DirectX 11.

**Comment by MrFrostyYT** [comment] 2018-02-01 10:19
Have you tried to re-download the software? Or maybe you've downloaded the wrong version?

**Comment by IMSCRUB** [comment] 2018-02-10 10:06
Nop, i'm download lastest version, and re-download TEdit and re-setup DX11 few times, nothing helps

**Comment by BinaryConstruct** [comment] 2018-02-26 19:28
Duplicate of #751

**Closed by BinaryConstruct** 2018-02-26 19:28 UTC
Labels: Bug
