### ISSUE TITLE
TEdit doesn't show textures!!

### ISSUE THREAD

**Issue by ombena** [TEdit/Terraria-Map-Editor#1035] opened 2017-11-18 17:06 UTC
Hello guys... i am having this issue where TEdit doesn't load any textures although i specifyed the path in the xml file... any help.
![capture](https://user-images.githubusercontent.com/33788107/32982875-930eb3dc-cc8b-11e7-98cc-e8b781d52ada.PNG)

## What were you doing when the issue occured?
i was trying to edit the tedit settings xml file to locate the content file 
## Can you reproduce the issue?
i think i can
## What version of Terraria are you using?
1.3.5.3(torrent download)
## Post relevant contents of log or attach log file _**(very important)**_:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/1484814/TEditLog.txt)

**Comment by BinaryConstruct** [comment] 2017-11-18 17:06
[GitMate.io](https://gitmate.io) thinks possibly duplicate or related issues are #1009 (Cannot Load World), #998 (Whenever I try to load a world, it comes up with an unhandled exception), #1015 (Can not open TEdit3_v3.10), #950 (what do i do if i have Windows XP :(), and #1024 (Unexpected error).

**Comment by BinaryConstruct** [comment] 2017-11-26 06:07
Duplicate of #751, please see there for tips.

**Closed by BinaryConstruct** 2017-11-26 06:07 UTC
Labels: Bug
