### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by CatLiteralJam** [TEdit/Terraria-Map-Editor#946] opened 2016-12-25 19:47 UTC
I opened it.
It Crashed.
No i can't reproduce the issue.
Plsfix.
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/672295/TEditLog.txt)

Using 1.3.4.4

**Comment by BinaryConstruct** [comment] 2016-12-29 19:09
This is a duplicate of #751, please look there for help.

**Closed by BinaryConstruct** 2016-12-29 19:09 UTC
