### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by LordNeptune** [TEdit/Terraria-Map-Editor#982] opened 2017-04-25 05:35 UTC
## What were you doing when the issue occured?
Starting the terraria

## Can you reproduce the issue?
yes

## What version of Terraria are you using?
1.3.5.2

[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/953959/TEditLog.txt)

I'm Brazilian, and i'dont speak english, I've used google translator intact, sorry.
This problem is persistent, I already tried moving to the desktop and executing as administrator but nothing works, please help me.

**Comment by BinaryConstruct** [comment] 2017-04-25 05:41
Duplicate of #751

**Closed by BinaryConstruct** 2017-04-25 05:41 UTC
