### ISSUE TITLE
World File Error

### ISSUE THREAD

**Issue by CynicalShrew** [TEdit/Terraria-Map-Editor#1220] opened 2020-05-21 21:00 UTC
When attempting to load one of my worlds, I get a message saying there was an error reading my world file. The world is a 1.4.0.1 world, and isn't corrupted from what I can tell. Forcing the world file to load doesn't cause any noticeable issues, aside from the missing textures for some of the plants, but that's normal. Newly created worlds open without any errors, as do 1.3 worlds. 

After making any changes, attempting to save the file will result in the message "[World Name] was externally modified since your last save. Do you wish to overwrite?" Clicking yes does nothing, and loading the world again or in-game shows the changes weren't saved. Not sure if any of this is useful, since it may just be my world that's the issue.

Here's the error message:
![Annotation 2020-05-21 135351](https://user-images.githubusercontent.com/55427406/82606022-433b7f00-9b6b-11ea-9f08-18392b592da1.png)

**Comment by BinaryConstruct** [comment] 2020-05-21 21:04
Duplicate of #1200

**Closed by BinaryConstruct** 2020-05-21 21:04 UTC

**Comment by CynicalShrew** [comment] 2020-05-21 21:05
I'll see if removing the weapon racks prevents the error.
