### ISSUE TITLE
The kill count will be reset to zero

### ISSUE THREAD

**Issue by imning3** [TEdit/Terraria-Map-Editor#1694] opened 2022-10-06 16:17 UTC
# READ THIS FIRST
- **Sprite Issues?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
- **Won't Start?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue
- **Map not loading?** See https://github.com/TEdit/Terraria-Map-Editor/wiki/Troubleshooting#application-launch-or-map-loading-issue

# If the Wiki did not help, fill out this form completely! If you are missing steps to reproduce your issue will be closed. Thank you.

**Before Submitting an Issue**
* If you are having issues loading a world, please attach it to the current version world thread (see pinned issues).
* For a crash, please check the log.

**Describe the bug**
What is the problem.

1. Click on '....'

**Expected behavior**
What you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [Tedit 4 beta 9]
 - Terraria Version [e.g. 1.4.0.4]

**Comment by Qunas101** [comment] 2022-10-07 18:57
Judging by the title it seems like you forgot to fill your issue. I just want to comment because I had the same issue.

I edited my world and counter that is displayed by the Tally Counter got reset. The new counter in the Bestiary (introduced in 1.4.4) is still correct, but Tally Counter completely reset to zero on all mobs.

Steps to reproduce the behavior:

- Save the world

**Expected behavior**
Bestiary and Tally Counter kill counters should match

Desktop:

- OS: Windows 10
- Tedit 4.11.0-beta2
- Terraria 1.4.4.3

**Comment by RussDev7** [comment] 2022-10-07 19:34
Tracking this thanks.

**Comment by WonderSquid** [comment] 2022-10-07 19:40
https://github.com/TEdit/Terraria-Map-Editor/issues/1670

Made this a while ago

**Comment by RussDev7** [comment] 2022-10-07 19:42
> #1670
> 
> Made this a while ago

Yes I saw, I have been collecting worlds to try and help solve this.

**Comment by mappy11** [comment] 2022-10-07 20:15
same

**Comment by pjpollina** [comment] 2022-10-07 20:16
Happened to me too, Bestiary kill counts seem to be unaffected.

**Comment by mappy11** [comment] 2022-10-07 20:20
> Happened to me too, Bestiary kill counts seem to be unaffected.

 Is kill count related to the world?Maybe this is where the answer is.

**Comment by Qunas101** [comment] 2022-10-07 20:29
> > Happened to me too, Bestiary kill counts seem to be unaffected.
> 
> Is kill count related to the world?Maybe this is where the answer is.

It is. Kills are stored per-world, It's weird that Bestiary is somehow separate from Tally Counter. I would assume they would be stored in the same place but guess not

**Comment by mappy11** [comment] 2022-10-07 20:32
> > > Happened to me too, Bestiary kill counts seem to be unaffected.
> > 
> > 
> > Is kill count related to the world?Maybe this is where the answer is.
> 
> It is. Kills are stored per-world, It's weird that Bestiary is somehow separate from Tally Counter. I would assume they would be stored in the same place but guess not

lol,trash code

**Comment by mappy11** [comment] 2022-10-07 20:34
> > > Happened to me too, Bestiary kill counts seem to be unaffected.
> > 
> > 
> > Is kill count related to the world?Maybe this is where the answer is.
> 
> It is. Kills are stored per-world, It's weird that Bestiary is somehow separate from Tally Counter. I would assume they would be stored in the same place but guess not

bro,do you have the same problem like #1695 ?

**Comment by RussDev7** [comment] 2022-10-07 20:49
> > > Happened to me too, Bestiary kill counts seem to be unaffected.
> > 
> > 
> > Is kill count related to the world?Maybe this is where the answer is.
> 
> It is. Kills are stored per-world, It's weird that Bestiary is somehow separate from Tally Counter. I would assume they would be stored in the same place but guess not

It used to unless it recently changed.

**Comment by pjpollina** [comment] 2022-10-07 21:10
Just wanted to point out that the beastiary tracks kills per-variant, while the tally count is per-group. So like, each different Zombie and Demon Eye sprite has its own counter separate from the sum "Zombie" or "Demon Eye" tally.

**Comment by Qunas101** [comment] 2022-10-07 22:03
Just looked at the wld file in hex and found that all bestiary entries are stored at the end with mob names, variants and kills and everything and it seems to be intact after editing. No idea where banner kills are, though

**Comment by WonderSquid** [comment] 2022-10-07 22:11
In general are mob kills stored little endian unsigned? Wanna know what to look for.

**Comment by WonderSquid** [comment] 2022-10-07 22:45
I might not know what the fuck I'm talking about because I am extremely new here, but I suspect the offsets for the tally counters themselves (which keep a slightly different count from the bestiary, since the different varieties of zombie are all counted as "zombie" for the tally) are stored from 0x1D0-66F. Give or take a few bytes anyway -- I'm not super clear on where it starts and ends because I'm not familiar with what the surrounding data is but I'm pretty sure I found the block itself.

**Comment by pjpollina** [comment] 2022-10-07 22:47
> out because I am extremely new here, but I suspect the offsets for the tally counters themselves (which keep a slightly different cou

You data miners are something else, mad respect.

**Comment by RussDev7** [comment] 2022-10-08 00:09
I'm looking to fix this now, sorry, been fixing a bunch of other stuff on TEdit. Does anyone have a world that has not been opened in 1.4.4+ yet?

**Comment by WonderSquid** [comment] 2022-10-08 00:13
I have one but will have to send it to you on Discord, it's not letting me attach .wld files in the comments for whatever reason. I also have a second world file and can confirm TEdit blanks the entire tally counter section upon save (and that I have the correct offset locations hooray).

**Comment by pjpollina** [comment] 2022-10-08 00:57
> I'm looking to fix this now, sorry, been fixing a bunch of other stuff on TEdit. Does anyone have a world that has not been opened in 1.4.4+ yet?

I might have a 1.4 world save circa Jan. 2021 if that'd help.

**Comment by RussDev7** [comment] 2022-10-08 01:24
> > I'm looking to fix this now, sorry, been fixing a bunch of other stuff on TEdit. Does anyone have a world that has not been opened in 1.4.4+ yet?
> 
> I might have a 1.4 world save circa Jan. 2021 if that'd help.

We might have found the issue. Hopefully I don't need it.

**Comment by WonderSquid** [comment] 2022-10-08 16:57
Listed the wrong offsets. Correct ones are 0x1F0-66F. Sorry for the misinformation.

**Comment by prochiral** [comment] 2022-10-13 22:48
Just to say that this was not fixed by the latest update, in fact, I experienced the bug for the first time when using Tedit 4.11. (Though the update did fix the biome morph, so thank you!!)

**Comment by RussDev7** [comment] 2022-10-13 23:41
> Just to say that this was not fixed by the latest update, in fact, I experienced the bug for the first time when using Tedit 4.11. (Though the update did fix the biome morph, so thank you!!)

This has been fixed in our latest dev build.

**Closed** 2022-10-15 17:51 UTC
Labels: Confirmed-Bug
