### ISSUE TITLE
Can't save (beta4 & beta5).

### ISSUE THREAD

**Issue by Natqo** [TEdit/Terraria-Map-Editor#1216] opened 2020-05-21 17:39 UTC
As my evil bioms grew larger I decided to purify the map with Tedit. Unfortunately my world won't save. Every time (no matter if its beta4 or beta5) it goes the same, firstly when I try to load my world it shows [this error](https://i.imgur.com/7SPLcZq.png), then I forceload it and make edits, finally when I try to save it with **Save As** option it just shows [this message](https://i.imgur.com/uZuyGEr.png), and I just press Yes and try to save it anyway but world file isn't created at all. Also in the bottom right corner it always says **Validating World...** but never progresses. My world I believe was created in version 1.3.5 and was still played on when 1.4 rolled out.

Here's what I'v already tried to fix the issue but didn't work:
- Using beta4, beta5 and TEdit 3.11
- Running TEdit with administrator privillages

## What were you doing when the issue occured?
Saving after editing (Purifying) my world.

## Can you reproduce the issue?
Yes, 100%

## What version of Terraria are you using?
1.4

## Post relevant contents of log or attach log file _**(very important)**_:
```05-21-2020 19:30:37: Starting TEdit 4.0.0.0 
05-21-2020 19:30:37: OS: Microsoft Windows NT 6.2.9200.0 
05-21-2020 19:30:37: Terraria v1.4.0.3 
05-21-2020 19:30:37: Terraria Data Path: D:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
05-21-2020 19:30:38: Creating Undo cache: C:\Users\natqo\AppData\Roaming\TEdit\undo_218179312 
```

**Comment by BinaryConstruct** [comment] 2020-05-21 17:50
Duplicate of #1200

**Closed by BinaryConstruct** 2020-05-21 17:50 UTC
