### ISSUE TITLE
TEdit didn't open

### ISSUE THREAD

**Issue by SuperGods10** [TEdit/Terraria-Map-Editor#1105] opened 2018-08-16 12:23 UTC
Win7 (64)
TEdit didn't open
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/2293661/TEditLog.txt)

**Comment by SuperGods10** [comment] 2018-08-16 12:27
What should I do?

**Comment by BinaryConstruct** [comment] 2018-08-16 21:07
This is a duplicate of #751

**Closed** 2018-08-16 21:07 UTC
