### ISSUE TITLE
Crashes when opening a world

### ISSUE THREAD

**Issue by Memoli345** [TEdit/Terraria-Map-Editor#1428] opened 2020-10-18 09:46 UTC
**Expected behavior**
TEdit crashes and sends the message that in screenshot, when i try opening my world.

**Screenshots**
![dgfdgf](https://user-images.githubusercontent.com/73058357/96363786-ffab6800-113e-11eb-9651-8ec63dbdfda7.JPG)

**Desktop**
 - OS: Windows 10
 - Version edit 4 beta33
 - Terraria Version 1.4.1.1

**This is the TEditLog.txt**

10-18-2020 12:33:08: Starting TEdit 4.0.0.0 
10-18-2020 12:33:08: OS: Microsoft Windows NT 10.0.18362.0 
10-18-2020 12:33:08: OS Name: Microsoft Windows 10 Pro  
10-18-2020 12:33:08: .NET Framework Version: 4.8 or later 
10-18-2020 12:33:08: Terraria v1.4.1.1 
10-18-2020 12:33:08: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
10-18-2020 12:33:09: Creating Undo cache: C:\Users\Beytaş\AppData\Roaming\TEdit\undo_342877589

**Comment by Memoli345** [comment] 2020-10-18 09:47
I think its becouse the new princess npc.

**Comment by xXmartin0311** [comment] 2020-10-18 10:01
It's being fixed, be patient

**Comment by BinaryConstruct** [comment] 2020-10-18 12:25
Duplicate of #1427

**Closed** 2020-10-18 12:24 UTC
