### ISSUE TITLE
System.OverflowException

### ISSUE THREAD

**Issue by Arthur-Kenichi-Condino** [TEdit/Terraria-Map-Editor#1183] opened 2020-05-17 20:40 UTC
## Before you submit an issue, please read
 * If you get an unhandled exception, please _**check your log before posting**_.
 * If your log includes _**DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved**_
   * This is a known issue, do not create a new issue, please add your comments to #751
   * People have had the most luck in Windows 7 with updating to DirectX 11.1
     This is found in windows update in the optional updates section or by
     following directions here 
   * https://support.microsoft.com/en-us/kb/179113
 * Please fill out the questions below
 * Instead of copy/pasting text you can attach the entire log file.
 * If your world file is less than 25MB, you can attach it as well.
   
## What were you doing when the issue occured?
Trying to get my city to the master mode. My backup 1.3 world opens fine but it's pretty old.

## Can you reproduce the issue?
get an old 1.3 world, play it in 1.4, close the game, then try to load it to the new Beta TEdit for 1.4 tool. It'll start loading, show a file format error, then after forcing to load, the tool will not present any errors but it'll close immediately.

## What version of Terraria are you using?
1.4

## Post relevant contents of log or attach log file _**(very important)**_:

in the file WorldViewModel.cs
at line 456
        public World CurrentWorld
        {
            get { return _currentWorld; }
            set { Set("CurrentWorld", ref _currentWorld, value); }//<=here, the following exception:
        }
An exception of type 'System.OverflowException' occurred in mscorlib.dll but was not handled in user code
Value was either too large or too small for an unsigned byte.

At VisualStudio Debug Mode:
This exception was originally thrown at this call stack:
	System.Convert.ToByte(int)
	System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
	MS.Internal.Data.DynamicValueConverter.Convert(object, System.Type, object, System.Globalization.CultureInfo)
	System.Windows.Controls.Primitives.Selector.VerifyEqual(object, System.Type, object, MS.Internal.Data.DynamicValueConverter)
	System.Windows.Controls.Primitives.Selector.FindItemWithValue(object, out int)
	System.Windows.Controls.Primitives.Selector.SelectItemWithValue(object, bool)
	System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(System.Windows.DependencyObject, object)
	System.Windows.DependencyObject.ProcessCoerceValue(System.Windows.DependencyProperty, System.Windows.PropertyMetadata, ref System.Windows.EntryIndex, ref int, ref System.Windows.EffectiveValueEntry, ref System.Windows.EffectiveValueEntry, ref object, object, object, System.Windows.CoerceValueCallback, bool, bool, bool)
	System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, ref System.Windows.EffectiveValueEntry, bool, bool, System.Windows.OperationType)
	System.Windows.DependencyObject.InvalidateProperty(System.Windows.DependencyProperty, bool)
    ...
    [Call Stack Truncated]

**Comment by Arthur-Kenichi-Condino** [comment] 2020-05-17 20:45
do you need help for checking and fixing these errors? I'm using VisualStudio here to test and check for the errors in debug mode, but I'm a little bit confused with the file formats and everything yet.

**Comment by Arthur-Kenichi-Condino** [comment] 2020-05-17 20:50
is it because the tile data now has more information and the unsigned byte value isn't enough or something like that?

**Comment by tomek-i** [comment] 2020-05-17 23:11
Just a guess, as I am at work and haven’t had a look yet, but converting int to byte was probably the cause of the overflow.

If you use VS, just to get you past the overflow you can change the data type to int or wrap it in try/catch and ignore the exception temporarily to get you past.

Once I get a breather I will load up the game again and have a look too and play around.

**Comment by Dogeislove** [comment] 2020-05-18 02:24
It must be because there is an overflow error. https://en.wikipedia.org/wiki/Buffer_overflow

**Comment by BinaryConstruct** [comment] 2020-05-18 14:58
This is already resolved in the code base, I have not updated the releases page.

**Closed by BinaryConstruct** 2020-05-18 14:58 UTC
